name: build and deploy
on:
  push:
    branches:
      - master
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Give permission to gradle
        run: cd android && chmod +x ./gradlew
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease
      - name: Generate Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Upload on server
        run: |
          scp android/app/build/outputs/apk/release/app-release.apk ${{ secrets.DEST }}
